# Generated by Django 4.0.4 on 2022-05-07 17:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=64)),
                ('date_of_birth', models.DateTimeField(blank=True, null=True)),
                ('date_of_death', models.DateTimeField(blank=True, null=True)),
                ('job', models.CharField(max_length=32)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='author', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('has_visited', models.BooleanField(default=False, help_text='Identify if the author has visited the alternate life')),
                ('visit_date', models.DateTimeField(blank=True, null=True)),
                ('days_stayed', models.PositiveIntegerField(default=0, help_text='The time spent in the life')),
                ('title', models.CharField(max_length=64)),
                ('description', models.TextField(help_text='Brief outlook into the expectations of the alternate life')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_liked', models.BooleanField(default=False)),
                ('comment', models.TextField(help_text='Experience of the alternative life')),
                ('life', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='midnight_library.book')),
            ],
        ),
        migrations.CreateModel(
            name='MidnightLibrary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='library', to='midnight_library.author')),
                ('manager', models.OneToOneField(help_text='The librarian/manager guiding the author through the library', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='library',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collection', to='midnight_library.midnightlibrary'),
        ),
    ]
